name: App Check

on:
  push:
    branches:
      - '*'
    paths:
      - src/**
      - .editorconfig
      - .eslintrc.js
      - .prettierrc.js
      - package.json
      - package-lock.json
      - tsconfig.json
  pull_request:
    branches:
      - '*'
    paths:
      - src/**
      - .editorconfig
      - .eslintrc.js
      - .prettierrc.js
      - package.json
      - package-lock.json
      - tsconfig.json
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - name: Install dependencies
        run: npm clean-install

      - name: Lint(ESLint)
        run: npm run -s lint:es

      - name: Lint(TypeScript)
        run: npm run -s lint:tsc
