name: Reusable workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Echo arguments
        run: echo username[${{inputs.username}}] token[${{secrets.envPAT}}]
